name: React Portfolio CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.1

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Clear ESLint cache
        run: rm -rf node_modules/.cache

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4

    - name: Deploy to Heroku via Git
      run: |
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        git push heroku main --force

